apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentgate.fullname" . }}-config
  labels:
    {{- include "agentgate.labels" . | nindent 4 }}
data:
  allowed-origins: {{ index (first .Values.ingress.hosts) "host" | quote }}
  nextauth-url: https://{{ index (first .Values.ingress.hosts) "host" }}
